# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dryvofront' do
  pod 'AppCenter/Crashes', '~> 1.13.2'
  pod 'AppCenter/Analytics', '~> 1.13.2'
  pod 'AppCenterReactNativeShared', '~> 1.12.2'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for dryvofront

  

  platform :ios, '9.0'
  target 'dryvofrontTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'dryvofront-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for dryvofront-tvOS

  target 'dryvofront-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
