export const LOAD_FETCH_SERVICE = "LOAD_FETCH_SERVICE"
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const ERROR = "ERROR"
export const TRUNCATE_ERROR = "TRUNCATE_ERROR"
export const CHANGE_USER_IMAGE = "CHANGE_USER_IMAGE"
