export const LOAD_FETCH_SERVICE = "LOAD_FETCH_SERVICE"
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const API_ERROR = "API_ERROR"
export const POP_ERROR = "POP_ERROR"
export const CHANGE_USER_IMAGE = "CHANGE_USER_IMAGE"
