export const TOKEN_KEY = "login_token"
export const REFRESH_TOKEN_KEY = "refresh_token"
export const ROOT_URL = "https://dryvo.herokuapp.com"
export const STORAGE_PREFIX = "Dryvo_"
export const DEFAULT_ERROR = "קרתה תקלה, אנא נסו שנית."
